services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warung_app
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - warung_network

  db:
    image: postgres:14-alpine
    container_name: warung_db
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - warung_db_data:/var/lib/postgresql/data
    networks:
      - warung_network

  redis:
    image: redis:6-alpine
    container_name: warung_redis
    ports:
      - "6379:6379"
    networks:
      - warung_network

volumes:
  warung_db_data:

networks:
  warung_network:
    driver: bridge